project: app-runtime-interfaces-wg
region: europe-west3
zone: europe-west3-a

team_name: app-autoscaler

github_repos:
  - name: app-autoscaler-release
    owner: cloudfoundry
    hpa_scaleup_trigger_duration: "10m"
    hpa_scaledown_delay_seconds: 0
    runnerset_resource_request_cpu: "800m"
    runnerset_resource_request_mem: "1500Mi"
    runnerset_resource_limits_cpu: "0m"
    runnerset_resource_limits_mem: "0Mi"

  - name: arc-test
    owner: marcinkubica
    hpa_scaleup_trigger_duration: "10m"
    hpa_scaledown_delay_seconds: 0
    runnerset_resource_request_cpu: "800m"
    runnerset_resource_request_mem: "1500Mi"
    runnerset_resource_limits_cpu: "0m"
    runnerset_resource_limits_mem: "0Mi"


#github_repo_name: app-autoscaler-release
#github_repo_owner: cloudfoundry

gcs_bucket: terraform-wg-ci-test
gcs_prefix: github-arc-team

dns_zone: app-runtime-interfaces
dns_domain: ci.cloudfoundry.org

# Your GKE cluster (assumes one already exists)
gke_name: wg-ci-test

# Github ARC runners node-pool config
github_arc_workers_pool_node_count: 1
github_arc_workers_pool_autoscaling_max: 4
github_arc_workers_pool_ssd_count: 0
github_arc_workers_pool_machine_type: n2-custom-8-16384

# Regional storage class type for team PVs
# see https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver#create_a_storageclass
gke_arc_storage_type: pd-ssd

# 4 runners on 8 core / 16g machine requests - cpu "1600m" memory: "3000Mi"
# 8 runners on 8 core / 16g machine requests - cpu "800m" memory: "1500Mi"
#runnerset_resource_request_cpu: "800m"
#runnerset_resource_request_mem: "1500Mi"

# resource limits for runner pods - 0m/0Mi to disable
#runnerset_resource_limits_cpu: "0m"
#runnerset_resource_limits_mem: "0Mi"

# Horisontal Pod (RunnerSet) Autoscaler tuning
#hpa_scaleup_trigger_duration: "10m"
#hpa_scaledown_delay_seconds: 0

arc_github_webhook_server_token_name: wg-ci-test-arc-webhook-server-token
arc_webhook_server_production_domain: app-runtime-interfaces.ci.cloudfoundry.org

tf_modules:
  github_arc:      "../..//terraform-modules/actions_runner_controller/team"