project: app-runtime-interfaces-wg
region: europe-west3
zone: europe-west3-a

# Your GKE cluster (assumes one already exists)
gke_name: wg-ci-test

# Github ARC workers config
github_arc_workers_pool_machine_type: n2-custom-8-16384
github_arc_workers_pool_node_count: 1
github_arc_workers_pool_autoscaling_max: 4
github_arc_workers_pool_ssd_count: 0

gcs_bucket: terraform-wg-ci-test
gcs_prefix: github-arc

cert_manager_helm_version: "1.10.1"
github_arc_helm_version: "0.21.1"

gsm_github_access_token_name: autoscaler-github-access-token

tf_modules:
  github_arc:      "../..//terraform-modules/github_arc"