project: app-runtime-interfaces-wg
region: europe-west3
zone: europe-west3-a

# Your GKE cluster (assumes one already exists)
gke_name: wg-ci-test
team_name: app-autoscaler

dns_zone: app-runtime-interfaces
dns_domain: ci.cloudfoundry.org

github_repo_name: app-autoscaler-release
github_repo_owner: cloudfoundry

# Github ARC workers config
github_arc_workers_pool_machine_type: n2-custom-8-16384
github_arc_workers_pool_node_count: 1
github_arc_workers_pool_autoscaling_max: 4
github_arc_workers_pool_ssd_count: 0

gcs_bucket: terraform-wg-ci-test
gcs_prefix: github-arc-team

arc_github_webhook_server_token_name: wg-ci-test-arc-webhook-server-token

arc_webhook_server_production_domain: app-runtime-interfaces.ci.cloudfoundry.org

tf_modules:
  github_arc:      "../..//terraform-modules/actions_runner_controller/team"